blacktop/go-macho

pkg/codesign/codesign.go

bug fix CodeDirectory Hash field allocate memory for it's own, no sharing memory

hash filed bytes array bug fix

---

export.go

The supplied resource directory slot hash was previously only being used when signing a binary that already had a code signature. There's no reason not to use it when creating a brand-new code signature, so this change does that.

codesign: always use supplied resource-directory hash if applicable

---

export.go
pkg/codesign/codesign.go

Mach-O code signing has a circular dependency problem: the code signature includes hashes that cover the link editing load-command which specifies the size of the code signature. Therefore we need to know the code signature's size before we generate it!
A proper code signature contains some potentially-rather-large components: the code hashes are proportional to the size of the binary itself, and the CMS signature can grow quite large because it includes the full signing certificate chain as well as a timestamp from the Apple timestamp service. This change computes a (somewhat conservative, but reasonable) estimate of code-signature size rather than merely aligning up to the nearest 16KiB boundary.

codesign: more conservative estimate of signature sizes

---

pkg/codesign/types/requirement.go

This change makes the inference of Designated Requirements from an Apple code-signing certificate chain more closely match the official Apple `codesign` tool:
- certs signed with a "developer id application" CA add a requirement for a signature by such a CA, a requirement for the leaf cert to have a "developer id application" extension (which we only add if the leaf cert in use does indeed have that extension), and bind the OU found the leaf cert
- certs signed with a "worldwide developer relations" CA (i.e., developer certificates) add a requirement for that CA extension, and bind the CN rather than the OU from the leaf cert
This is important because two binaries must have identical Designated Requirements in order to be considered the same application by macOS.

requirements: correctly interpret apple cert requirements

---

export.go
file.go
pkg/codesign/codesign.go

This change adds support for the RUNTIME code signature flag, which requires a hardened runtime and allows the binary to require a particular runtime version.

codesign: add support for RUNTIME flag and minimum runtime version

---

types/objc/type_encoding.go

When a type the implements multiple protocols, go-macho doesn't encode it properly. This patch addresses this issue.
Before:
```objc
@protocol APMetricNotificationRegisterOwner <NSObject>
@property (readonly, nonatomic) NSObject<APMetricNotificationRegister><APMetricReceiving> *notificationRegistrar;
@end
```
After:
```objc
@protocol APMetricNotificationRegisterOwner <NSObject>
@property (readonly, nonatomic) NSObject<APMetricNotificationRegister, APMetricReceiving> *notificationRegistrar;
@end
```

fix: type encoding when implementing multiple protocols

---

types/objc/category.go
types/objc/class.go
types/objc/protocol.go

The `@optional` directive of Objective-C defines that all property and method definitions bellow it are optional. This only changes if a `@required` directive is placed bellow it. go-macho doesn't implement this properly and mistakenly declares required methods as optional.
Additionally, `@required` and `@optional` should only ever be used inside `@protocol` blocks. But go-macho also uses them in `@interface` blocks.
This patch fixes both issues.
As I have tweaked the formatting of generated code slightly, I also changed the formatting of categories to keep consistency.
Before:
```objc
@protocol UIActivityItemsConfigurationReading <NSObject>
@property (readonly, copy, nonatomic) NSArray *itemProvidersForActivityItemsConfiguration;
@optional
@property (readonly, copy, nonatomic) NSArray …
```

fix: use of @optional directive in protocols and interfaces

---

types/objc/type_encoding.go

`@dynamic` is only meant to be used inside an `@implementation` block, it should never appear inside `@interface` and `@protocol` blocks. This patch prevents go-macho from generating a header with that attribute.
Before:
```objc
@interface AXAuditTimedResult : NSObject
@property (retain, nonatomic) NSDate *startTime;
@property (retain, nonatomic) NSDate *endTime;
@property (readonly, @dynamic, nonatomic) NSString *executionTimeString;
@end
```
After:
```objc
@interface AXAuditTimedResult : NSObject
@property (retain, nonatomic) NSDate *startTime;
@property (retain, nonatomic) NSDate *endTime;
@property (readonly, nonatomic) NSString *executionTimeString;
@end
```

fix: omit dynamic from property attributes

---

types/objc/type_encoding.go

Objects that conform to a protocol are not required to conform to `NSObject`. This patch makes go-macho use `id` instead of `NSObject` when referring to a type that conforms to some protocol.

fix: conforming to a protocol does not imply in conforming to NSObject

---

types/objc/type_encoding.go

`id` should not be followed by `*`. This should've been addressed in the `NSObject` to `id` PR.
Before:
```objc
@interface SORequestQueueItem : NSObject <SOQueueItem>
@property (readonly, nonatomic) id <SOServiceProtocol> *service;
```
After:
```objc
@interface SORequestQueueItem : NSObject <SOQueueItem>
@property (readonly, nonatomic) id <SOServiceProtocol> service;
```

fix: id followed by *

---

types/objc/type_encoding.go

We should always replace `><` with `, `, not only when we have untyped protocol qualifiers.
Before:
```objc
@import Foundation;
@protocol NSFilePresenterXPCInterface><NSXPCProxyCreating;
@interface NSFilePresenterManagedProxy : NSObject <NSXPCProxyCreating> {
/* instance variables */
NSObject<NSFilePresenterXPCInterface><NSXPCProxyCreating> *_xpcProxy;
NSObject<NSFilePresenterXPCInterface><NSXPCProxyCreating> *_nonboostingXPCProxy;
}
```
After:
```objc
@import Foundation;
@interface NSFilePresenterManagedProxy : NSObject <NSXPCProxyCreating> {
/* instance variables */
NSObject<NSFilePresenterXPCInterface, NSXPCProxyCreating> *_xpcProxy;
NSObject<NSFilePresenterXPCInterface, NSXPCProxyCreating> *_nonboostingXPCProxy;
}
```

fix: always replace `><` with `, `

---

types/objc/type_encoding.go

Changes to types map:
- set `B` to `_Bool`, because `@encode(_Bool) == "B" && @encode(BOOL) == "c"`
- set `t` to `__int128`, because `int128` is undeclared identifier
- set `T` to `unsigned __int128`, because `int128` is undeclared identifier
- set `?` to `void * /* unknown */`, because `undefined` is undeclared identifier
- set `^?` to `void * /* function */`, because `@encode(typeof(&main)) == "^?"` and to distinguish from `^v`
- unset `Vv`, because `@encode(oneway void) == "Vv"`
Changes to modifiers map:
- set `O` to `bycopy`, because `by` and `copy` are undeclared identifiers
- set `R` to `byref`, because `by` and `ref` are undeclared identifiers
- set `V` to `oneway`, because `one` and `way` are undeclared identifiers
Changes to decoding function:
- check types map before checking if …

fix: review obj-c type encoding

---

types/objc/type_encoding.go

I did some research and reviewed all types encodings and made some changes. Also added a new list of references and various comments clarifying types.
About `!`, I've found out that it represents non-standard vector types ([GNU](https://gcc.gnu.org/onlinedocs/gcc/Vector-Extensions.html) and [LLVM](https://clang.llvm.org/docs/LanguageExtensions.html#vectors-and-extended-vectors)). `gcc` is able encode these types in Objective-C but `clang` fails with _Encoding of 'v4si' (vector of 4 'int' values) type is incomplete because 'v4si' component has unknown encoding_. I'll be implementing the encoding for these types latter this week.
I just learned that C has a half-precision floating-point types: `__bf16`, `__fp16`, `_Float16`. The latter is the portable version and `clang` encodes it using …

fix: type encoding for Objective-C

---

types/objc/type_encoding.go
types/objc/type_encoding_test.go

Implements decoding for GNU Vectors.
Reference: https://gcc.gnu.org/onlinedocs/gcc/Type-encoding.html

feat: decode vectors

---

types/objc/type_encoding.go
types/objc/type_encoding_test.go

`go-macho` doesn't handle named members properly for all types and generates invalid definitions for unknown structs and unions. This patch addresses these issues.
1. Named Member
- Before:
```objc
@interface PKInstallDaemonClient : NSObject <PKInstallService, PKInstallServiceClient> {
struct { unsigned int x[8] val; } _clientAuditToken;
```
- After:
```objc
@interface PKInstallDaemonClient : NSObject <PKInstallService, PKInstallServiceClient> {
struct { unsigned int val[8]; } _clientAuditToken;
```
2. Unknown Struct
- Before:
```objc
@interface PKInstallRequest : NSObject <NSSecureCoding> {
struct { unsigned int x0; struct  *x1; } * _authorizationEnvironment;
```
- After:
```objc
@interface PKInstallRequest : NSObject <NSSecureCoding> {
struct { unsigned int x0; void * /* struct */ x1; } …
```

fix: struct and union decoding

---

types/objc/type_encoding.go

Sometimes, the generated argument name for methods collide with reserved words. This patch simplifies the name of method arguments to prevent these collisions.
- Before:
```objc
@interface AMSBagUnderlyingDataPersistence
- (id)underlyingDataFor:(id)for error:(id *)_error;
```
- After:
```objc
@interface AMSBagUnderlyingDataPersistence
- (id)underlyingDataFor:(id)arg0 error:(id *)arg1;
```

fix: method argument name collision

---

types/objc/type_encoding.go
types/objc/type_encoding_test.go

Add missing type specifiers to fix struct and union parsing.
Before:
```objc
@class __cached_isReady, __isCancelled, __isCancelledObserverCount, __isExecutingObserverCount, __isFinishedObserverCount, __isReadyObserverCount, __propertyQoS, __state;
@protocol OS_voucher;
@interface NSOperation : NSObject {
/* instance variables */
struct { NSOperation *__prevOp; NSOperation *__nextOp; NSOperation *__nextPriOp; NSOperationQueue *__queue; NSMutableArray *__dependencies; NSHashTable *__down_dependencies; long long __unfinished_deps; id /* block */ __completion; void *__obsInfo; void *__implicitObsInfo; double __thread_prio; char *__nameBuffer; NSObject<OS_voucher> *_voucher; id /* block */ __schedule; struct _opaque_pthread_mutex_t { long long __sig; signed char __opaque[56]; } __wait_mutex; …
```

fix: struct fields with specifiers

---

types/objc/type_encoding.go
types/objc/type_encoding_test.go

The `@"` sequence is ambiguous when used inside structs and unions. This patch makes go-macho correctly decode these types based on the behaviour of clang.
| Encoded Type | Decoded Type |
| - | - |
| `{S="Id"@"NSString"^{S}}` | `struct S { id Id; struct S *NSString; }`
| `{S="Id"@"NSString""NSString"^{S}}` | `struct S { NSString *Id; struct S *NSString; }`
| `{?=@"NSString"^{S}}` | `struct { NSString *; struct S *; }`
Before:
```objc
@class next;
@interface __CFPrefsWeakObservers : NSObject <NSMutableCopying> {
/* instance variables */
struct __cfobservers_t { next *slot; struct __cfobservers_t *x1; } values;
```
After:
```objc
@interface __CFPrefsWeakObservers : NSObject <NSMutableCopying> {
/* instance variables */
struct __cfobservers_t { id slot; struct __cfobservers_t *next; } …
```

fix: decoding struct and union fields with ambiguous types

---

types/objc/type_encoding.go
types/objc/type_encoding_test.go

Fix bug where of types containing arrays wouldn't get decoded properly.
- Before
```objc
@interface IDSGlobalLinkMessage : NSObject {
/* instance variables */
C]})} x[20{IDSGlobalLinkAttribute="type"S"len"S"value"(?="ss"{sockaddr_storage="ss_len"C"ss_family"C"__ss_pad1"[6c]"__ss_align"q"__ss_pad2"[112c]}"u16"S"u32"I"u64"Q"binaryData"{IDSGLAttrBinaryData_="len"i"data"[1024] _attributes;
```
- After
```objc
@interface IDSGlobalLinkMessage : NSObject {
/* instance variables */
struct IDSGlobalLinkAttribute { unsigned short type; unsigned short len; union { struct sockaddr_storage { unsigned char ss_len; unsigned char ss_family; signed char __ss_pad1[6]; long long __ss_align; signed char __ss_pad2[112]; } ss; unsigned short u16; unsigned int u32; unsigned long long u64; struct …
```

fix: array decoding

---

export.go

When we are creating a new CodeSignature, we align its offset up to a multiple of the page size; we then read the existing LINKEDIT section (and the entire beginning of the file, for signing) based on the location of that code signature. If the existing LINKEDIT section's end was not page-aligned, we get an EOF when attempting to read up to the page-aligned flie size, causing signing to fail.
This change limits our read to the actual size of the file (or LINKEDIT section, at least), while keeping the buffer we read into the correct size (and therefore implicitly padding it with zeroes, which will get written out when we rewrite the LINKEDIT section and new signature).
I had never encountered this bug before because we'd never seen a MachO whose LINKEDIT section didn't end on a page …

fix(codesign): pad LINKEDIT to multiple of page size when reading

---

pkg/trie/trie.go

Addends of Mach-O Binding Info were not matching the values from `dyld_info -symbolic_fixups`. This problem was caused by a bug in the implementation of `ReadSleb128`. Fixing this bug addressed the problem with the addends.
```console
+0x0000      bind pointer   IOKit/_IOServiceMatching+54
+0x0008      bind pointer   CoreFoundation/_CFDictionaryCreateMutable+5067
+0x0010      bind pointer   CoreFoundation/_CFStringCreateWithCString+4672
+0x0018      bind pointer   CoreFoundation/_CFDictionarySetValue+1754
+0x0020      bind pointer   CoreFoundation/_CFRelease+83
+0x0028      bind pointer   IOKit/_IOServiceGetMatchingServices+600
+0x0030      bind pointer   IOKit/_IORegistryEntryGetParentEntry+2510
+0x0038      bind pointer   IOKit/_IORegistryEntryCreateCFProperty+4336
+0x0040      bind …
```

Fix ReadSleb128

---

pkg/xar/xar.go

This patch makes `OpenRaw` return `SectionReader` instead `ReadCloser` to allow random access to the underlying file.

make OpenRaw return SectionReader
